admin:
    asl: 30
    description: Dalgety Bay SDR operated by <a href="https://qrz.com/db/mm3ndh" target="_blank">MM3NDH</a>
    email: mm3ndh@nsamail.uk
    gps:
        lat: 56.04035
        lon: -3.35542
    location: Dalgety Bay, Scotland, UK
    name: MM3NDH SDR with 40m Loop
    password: PKa66sAy@Y5fZq9p
    version: v1.2.40
audio:
    buffer_size: 4096
    default_sample_rate: 12000
    mode_sample_rates:
        am: 12000
        cwl: 12000
        cwu: 12000
        fm: 24000
        iq: 192000
        lsb: 12000
        nfm: 24000
        sam: 12000
        usb: 12000
    opus:
        bitrate: 48000
        complexity: 5
        enabled: false
logging:
    format: text
    level: info
radiod:
    data_group: pcm.local:5004
    interface: ""
    status_group: hf-status.local:5006
server:
    cmd_rate_limit: 10
    enable_cors: false
    listen: :8080
    logfile: web.log
    max_session_time: 0
    max_sessions: 20
    max_sessions_ip: 2
    session_timeout: 3600
    timeout_bypass_ips:
        - 127.0.0.1
spectrum:
    default:
        bin_bandwidth: 29296.875
        bin_count: 1024
        center_frequency: 1.5e+07
    enabled: true
    gain_db: 15
    max_sessions_per_user: 2
    poll_period_ms: 100
    smoothing:
        enabled: true
        spatial_sigma: 1.5
        temporal_alpha: 0.3
