// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ubersdr_dsp.proto

package dsp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PcmEncoding int32

const (
	// IEEE 754 float32, little-endian (default — existing behaviour).
	PcmEncoding_PCM_FLOAT32_LE PcmEncoding = 0
	// Signed 16-bit integer, big-endian (radiod / ubersdr native format).
	// Inbound:  int16 BE bytes → float32 = int16(BE) / 32768.0
	// Outbound: float32 → int16 BE bytes = clamp(f * 32768.0) as big-endian int16
	PcmEncoding_PCM_INT16_BE PcmEncoding = 1
)

// Enum value maps for PcmEncoding.
var (
	PcmEncoding_name = map[int32]string{
		0: "PCM_FLOAT32_LE",
		1: "PCM_INT16_BE",
	}
	PcmEncoding_value = map[string]int32{
		"PCM_FLOAT32_LE": 0,
		"PCM_INT16_BE":   1,
	}
)

func (x PcmEncoding) Enum() *PcmEncoding {
	p := new(PcmEncoding)
	*p = x
	return p
}

func (x PcmEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PcmEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_ubersdr_dsp_proto_enumTypes[0].Descriptor()
}

func (PcmEncoding) Type() protoreflect.EnumType {
	return &file_ubersdr_dsp_proto_enumTypes[0]
}

func (x PcmEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PcmEncoding.Descriptor instead.
func (PcmEncoding) EnumDescriptor() ([]byte, []int) {
	return file_ubersdr_dsp_proto_rawDescGZIP(), []int{0}
}

type AudioRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AudioRequest_Config
	//	*AudioRequest_Audio
	//	*AudioRequest_ParamUpdate
	Payload       isAudioRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioRequest) Reset() {
	*x = AudioRequest{}
	mi := &file_ubersdr_dsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioRequest) ProtoMessage() {}

func (x *AudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ubersdr_dsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioRequest.ProtoReflect.Descriptor instead.
func (*AudioRequest) Descriptor() ([]byte, []int) {
	return file_ubersdr_dsp_proto_rawDescGZIP(), []int{0}
}

func (x *AudioRequest) GetPayload() isAudioRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AudioRequest) GetConfig() *SessionConfig {
	if x != nil {
		if x, ok := x.Payload.(*AudioRequest_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *AudioRequest) GetAudio() *AudioChunk {
	if x != nil {
		if x, ok := x.Payload.(*AudioRequest_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *AudioRequest) GetParamUpdate() *ParamUpdate {
	if x != nil {
		if x, ok := x.Payload.(*AudioRequest_ParamUpdate); ok {
			return x.ParamUpdate
		}
	}
	return nil
}

type isAudioRequest_Payload interface {
	isAudioRequest_Payload()
}

type AudioRequest_Config struct {
	// First message on the stream: selects filter and sets initial params.
	// Sending a second SessionConfig mid-stream is rejected.
	Config *SessionConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type AudioRequest_Audio struct {
	// Raw PCM audio frames to process.
	Audio *AudioChunk `protobuf:"bytes,2,opt,name=audio,proto3,oneof"`
}

type AudioRequest_ParamUpdate struct {
	// Real-time parameter update — accepted any time after SessionConfig.
	// Only the params you want to change need to be included.
	ParamUpdate *ParamUpdate `protobuf:"bytes,3,opt,name=param_update,json=paramUpdate,proto3,oneof"`
}

func (*AudioRequest_Config) isAudioRequest_Payload() {}

func (*AudioRequest_Audio) isAudioRequest_Payload() {}

func (*AudioRequest_ParamUpdate) isAudioRequest_Payload() {}

type SessionConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter name: "nr2" | "rn2" | "nr4" | "dfnr" | "bnr"
	Filter string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// Advisory chunk size hint, in frames at the client sample rate.
	// The server accepts AudioChunk payloads of ANY size — all filters handle
	// variable-length input via internal accumulators.  When block > 0 it is
	// used only as a buffer-size hint for the r8brain resampler (relevant when
	// sample_rate != 24000); it does not constrain the pcm_data length.
	// Set to 0 (or omit) to let the server use its default hint of 960 frames.
	Block int32 `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	// Initial parameter values as string key/value pairs.
	// Keys match the CLI flag names without leading "--" (e.g. "gain-method", "reduction").
	Params map[string]string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Sample rate of the audio sent by the client, in Hz.
	// Supported values: 12000, 24000 (default: 24000).
	// The server resamples to/from its internal 24 kHz processing rate transparently.
	// The response AudioChunks are returned at the same sample rate as the request.
	SampleRate int32 `protobuf:"varint,4,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	// Number of channels in the client audio (1 = mono, 2 = stereo, default: 2).
	// Mono input is expanded to stereo internally before processing and collapsed
	// back to mono in the response. All filters process stereo internally.
	Channels int32 `protobuf:"varint,5,opt,name=channels,proto3" json:"channels,omitempty"`
	// Wire encoding of pcm_data in AudioChunk messages (default: PCM_FLOAT32_LE).
	// Set to PCM_INT16_BE when the client sends signed 16-bit big-endian samples
	// (e.g. radiod / ubersdr). The server converts transparently on both ingest
	// and egress; all internal processing remains float32 little-endian.
	PcmEncoding   PcmEncoding `protobuf:"varint,6,opt,name=pcm_encoding,json=pcmEncoding,proto3,enum=ubersdr.dsp.v1.PcmEncoding" json:"pcm_encoding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionConfig) Reset() {
	*x = SessionConfig{}
	mi := &file_ubersdr_dsp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionConfig) ProtoMessage() {}

func (x *SessionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ubersdr_dsp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionConfig.ProtoReflect.Descriptor instead.
func (*SessionConfig) Descriptor() ([]byte, []int) {
	return file_ubersdr_dsp_proto_rawDescGZIP(), []int{1}
}

func (x *SessionConfig) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *SessionConfig) GetBlock() int32 {
	if x != nil {
		return x.Block
	}
	return 0
}

func (x *SessionConfig) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *SessionConfig) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *SessionConfig) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *SessionConfig) GetPcmEncoding() PcmEncoding {
	if x != nil {
		return x.PcmEncoding
	}
	return PcmEncoding_PCM_FLOAT32_LE
}

type ParamUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parameters to update. Only included keys are changed; others are untouched.
	Params        map[string]string `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamUpdate) Reset() {
	*x = ParamUpdate{}
	mi := &file_ubersdr_dsp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamUpdate) ProtoMessage() {}

func (x *ParamUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_ubersdr_dsp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamUpdate.ProtoReflect.Descriptor instead.
func (*ParamUpdate) Descriptor() ([]byte, []int) {
	return file_ubersdr_dsp_proto_rawDescGZIP(), []int{2}
}

func (x *ParamUpdate) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type AudioChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PCM audio data in the format declared by SessionConfig.pcm_encoding.
	// Any length is accepted provided it is a whole number of frames:
	//
	//	PCM_FLOAT32_LE: len % (channels * 4) == 0
	//	PCM_INT16_BE:   len % (channels * 2) == 0
	//
	// The server processes whatever arrives; no fixed block size is required.
	PcmData []byte `protobuf:"bytes,1,opt,name=pcm_data,json=pcmData,proto3" json:"pcm_data,omitempty"`
	// Monotonic counter for ordering / loss detection.
	SequenceNum uint64 `protobuf:"varint,2,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	// Optional: source capture timestamp in microseconds.
	TimestampUs   uint64 `protobuf:"varint,3,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_ubersdr_dsp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_ubersdr_dsp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_ubersdr_dsp_proto_rawDescGZIP(), []int{3}
}

func (x *AudioChunk) GetPcmData() []byte {
	if x != nil {
		return x.PcmData
	}
	return nil
}

func (x *AudioChunk) GetSequenceNum() uint64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *AudioChunk) GetTimestampUs() uint64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

type AudioResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AudioResponse_Audio
	//	*AudioResponse_Ack
	//	*AudioResponse_Error
	Payload isAudioResponse_Payload `protobuf_oneof:"payload"`
	// Session identifier assigned by the server on the first response.
	SessionId     string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioResponse) Reset() {
	*x = AudioResponse{}
	mi := &file_ubersdr_dsp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioResponse) ProtoMessage() {}

func (x *AudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ubersdr_dsp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioResponse.ProtoReflect.Descriptor instead.
func (*AudioResponse) Descriptor() ([]byte, []int) {
	return file_ubersdr_dsp_proto_rawDescGZIP(), []int{4}
}

func (x *AudioResponse) GetPayload() isAudioResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AudioResponse) GetAudio() *AudioChunk {
	if x != nil {
		if x, ok := x.Payload.(*AudioResponse_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *AudioResponse) GetAck() *ParamAck {
	if x != nil {
		if x, ok := x.Payload.(*AudioResponse_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *AudioResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Payload.(*AudioResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *AudioResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type isAudioResponse_Payload interface {
	isAudioResponse_Payload()
}

type AudioResponse_Audio struct {
	// Processed PCM audio (same format as input).
	Audio *AudioChunk `protobuf:"bytes,1,opt,name=audio,proto3,oneof"`
}

type AudioResponse_Ack struct {
	// Acknowledgement of a ParamUpdate.
	Ack *ParamAck `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type AudioResponse_Error struct {
	// Error notification (stream remains open unless the server closes it).
	Error *ErrorResponse `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*AudioResponse_Audio) isAudioResponse_Payload() {}

func (*AudioResponse_Ack) isAudioResponse_Payload() {}

func (*AudioResponse_Error) isAudioResponse_Payload() {}

type ParamAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parameters that were successfully applied (key → value actually set).
	Applied map[string]string `protobuf:"bytes,1,rep,name=applied,proto3" json:"applied,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Parameters that were rejected (key → reason string).
	Rejected      map[string]string `protobuf:"bytes,2,rep,name=rejected,proto3" json:"rejected,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamAck) Reset() {
	*x = ParamAck{}
	mi := &file_ubersdr_dsp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamAck) ProtoMessage() {}

func (x *ParamAck) ProtoReflect() protoreflect.Message {
	mi := &file_ubersdr_dsp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamAck.ProtoReflect.Descriptor instead.
func (*ParamAck) Descriptor() ([]byte, []int) {
	return file_ubersdr_dsp_proto_rawDescGZIP(), []int{5}
}

func (x *ParamAck) GetApplied() map[string]string {
	if x != nil {
		return x.Applied
	}
	return nil
}

func (x *ParamAck) GetRejected() map[string]string {
	if x != nil {
		return x.Rejected
	}
	return nil
}

type ErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error codes:
	//
	//	FILTER_CHANGE_NOT_ALLOWED — SessionConfig sent after stream is configured
	//	NOT_CONFIGURED            — AudioChunk or ParamUpdate before SessionConfig
	//	FILTER_INIT_FAILED        — filter constructor failed (e.g. model not found)
	//	INVALID_PARAM             — malformed param in SessionConfig.params
	//	UNKNOWN_FILTER            — unrecognised filter name
	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_ubersdr_dsp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ubersdr_dsp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_ubersdr_dsp_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetFiltersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFiltersRequest) Reset() {
	*x = GetFiltersRequest{}
	mi := &file_ubersdr_dsp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFiltersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFiltersRequest) ProtoMessage() {}

func (x *GetFiltersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ubersdr_dsp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFiltersRequest.ProtoReflect.Descriptor instead.
func (*GetFiltersRequest) Descriptor() ([]byte, []int) {
	return file_ubersdr_dsp_proto_rawDescGZIP(), []int{7}
}

type GetFiltersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*FilterInfo          `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFiltersResponse) Reset() {
	*x = GetFiltersResponse{}
	mi := &file_ubersdr_dsp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFiltersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFiltersResponse) ProtoMessage() {}

func (x *GetFiltersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ubersdr_dsp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFiltersResponse.ProtoReflect.Descriptor instead.
func (*GetFiltersResponse) Descriptor() ([]byte, []int) {
	return file_ubersdr_dsp_proto_rawDescGZIP(), []int{8}
}

func (x *GetFiltersResponse) GetFilters() []*FilterInfo {
	if x != nil {
		return x.Filters
	}
	return nil
}

type FilterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Params        []*ParamInfo           `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterInfo) Reset() {
	*x = FilterInfo{}
	mi := &file_ubersdr_dsp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterInfo) ProtoMessage() {}

func (x *FilterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ubersdr_dsp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterInfo.ProtoReflect.Descriptor instead.
func (*FilterInfo) Descriptor() ([]byte, []int) {
	return file_ubersdr_dsp_proto_rawDescGZIP(), []int{9}
}

func (x *FilterInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FilterInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FilterInfo) GetParams() []*ParamInfo {
	if x != nil {
		return x.Params
	}
	return nil
}

type ParamInfo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type        string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "float" | "int" | "bool"
	DefaultVal  string                 `protobuf:"bytes,3,opt,name=default_val,json=defaultVal,proto3" json:"default_val,omitempty"`
	MinVal      string                 `protobuf:"bytes,4,opt,name=min_val,json=minVal,proto3" json:"min_val,omitempty"`
	MaxVal      string                 `protobuf:"bytes,5,opt,name=max_val,json=maxVal,proto3" json:"max_val,omitempty"`
	Description string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// All parameters in this service are runtime-safe (atomic setters).
	RuntimeSafe   bool `protobuf:"varint,7,opt,name=runtime_safe,json=runtimeSafe,proto3" json:"runtime_safe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamInfo) Reset() {
	*x = ParamInfo{}
	mi := &file_ubersdr_dsp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamInfo) ProtoMessage() {}

func (x *ParamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ubersdr_dsp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamInfo.ProtoReflect.Descriptor instead.
func (*ParamInfo) Descriptor() ([]byte, []int) {
	return file_ubersdr_dsp_proto_rawDescGZIP(), []int{10}
}

func (x *ParamInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParamInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ParamInfo) GetDefaultVal() string {
	if x != nil {
		return x.DefaultVal
	}
	return ""
}

func (x *ParamInfo) GetMinVal() string {
	if x != nil {
		return x.MinVal
	}
	return ""
}

func (x *ParamInfo) GetMaxVal() string {
	if x != nil {
		return x.MaxVal
	}
	return ""
}

func (x *ParamInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ParamInfo) GetRuntimeSafe() bool {
	if x != nil {
		return x.RuntimeSafe
	}
	return false
}

var File_ubersdr_dsp_proto protoreflect.FileDescriptor

const file_ubersdr_dsp_proto_rawDesc = "" +
	"\n" +
	"\x11ubersdr_dsp.proto\x12\x0eubersdr.dsp.v1\"\xc8\x01\n" +
	"\fAudioRequest\x127\n" +
	"\x06config\x18\x01 \x01(\v2\x1d.ubersdr.dsp.v1.SessionConfigH\x00R\x06config\x122\n" +
	"\x05audio\x18\x02 \x01(\v2\x1a.ubersdr.dsp.v1.AudioChunkH\x00R\x05audio\x12@\n" +
	"\fparam_update\x18\x03 \x01(\v2\x1b.ubersdr.dsp.v1.ParamUpdateH\x00R\vparamUpdateB\t\n" +
	"\apayload\"\xb8\x02\n" +
	"\rSessionConfig\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\x12\x14\n" +
	"\x05block\x18\x02 \x01(\x05R\x05block\x12A\n" +
	"\x06params\x18\x03 \x03(\v2).ubersdr.dsp.v1.SessionConfig.ParamsEntryR\x06params\x12\x1f\n" +
	"\vsample_rate\x18\x04 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x05 \x01(\x05R\bchannels\x12>\n" +
	"\fpcm_encoding\x18\x06 \x01(\x0e2\x1b.ubersdr.dsp.v1.PcmEncodingR\vpcmEncoding\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\vParamUpdate\x12?\n" +
	"\x06params\x18\x01 \x03(\v2'.ubersdr.dsp.v1.ParamUpdate.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\n" +
	"AudioChunk\x12\x19\n" +
	"\bpcm_data\x18\x01 \x01(\fR\apcmData\x12!\n" +
	"\fsequence_num\x18\x02 \x01(\x04R\vsequenceNum\x12!\n" +
	"\ftimestamp_us\x18\x03 \x01(\x04R\vtimestampUs\"\xd2\x01\n" +
	"\rAudioResponse\x122\n" +
	"\x05audio\x18\x01 \x01(\v2\x1a.ubersdr.dsp.v1.AudioChunkH\x00R\x05audio\x12,\n" +
	"\x03ack\x18\x02 \x01(\v2\x18.ubersdr.dsp.v1.ParamAckH\x00R\x03ack\x125\n" +
	"\x05error\x18\x03 \x01(\v2\x1d.ubersdr.dsp.v1.ErrorResponseH\x00R\x05error\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionIdB\t\n" +
	"\apayload\"\x88\x02\n" +
	"\bParamAck\x12?\n" +
	"\aapplied\x18\x01 \x03(\v2%.ubersdr.dsp.v1.ParamAck.AppliedEntryR\aapplied\x12B\n" +
	"\brejected\x18\x02 \x03(\v2&.ubersdr.dsp.v1.ParamAck.RejectedEntryR\brejected\x1a:\n" +
	"\fAppliedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rRejectedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11GetFiltersRequest\"J\n" +
	"\x12GetFiltersResponse\x124\n" +
	"\afilters\x18\x01 \x03(\v2\x1a.ubersdr.dsp.v1.FilterInfoR\afilters\"u\n" +
	"\n" +
	"FilterInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x121\n" +
	"\x06params\x18\x03 \x03(\v2\x19.ubersdr.dsp.v1.ParamInfoR\x06params\"\xcb\x01\n" +
	"\tParamInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vdefault_val\x18\x03 \x01(\tR\n" +
	"defaultVal\x12\x17\n" +
	"\amin_val\x18\x04 \x01(\tR\x06minVal\x12\x17\n" +
	"\amax_val\x18\x05 \x01(\tR\x06maxVal\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12!\n" +
	"\fruntime_safe\x18\a \x01(\bR\vruntimeSafe*3\n" +
	"\vPcmEncoding\x12\x12\n" +
	"\x0ePCM_FLOAT32_LE\x10\x00\x12\x10\n" +
	"\fPCM_INT16_BE\x10\x012\xb2\x01\n" +
	"\n" +
	"DspService\x12O\n" +
	"\fProcessAudio\x12\x1c.ubersdr.dsp.v1.AudioRequest\x1a\x1d.ubersdr.dsp.v1.AudioResponse(\x010\x01\x12S\n" +
	"\n" +
	"GetFilters\x12!.ubersdr.dsp.v1.GetFiltersRequest\x1a\".ubersdr.dsp.v1.GetFiltersResponseB\x03\x80\x01\x00b\x06proto3"

var (
	file_ubersdr_dsp_proto_rawDescOnce sync.Once
	file_ubersdr_dsp_proto_rawDescData []byte
)

func file_ubersdr_dsp_proto_rawDescGZIP() []byte {
	file_ubersdr_dsp_proto_rawDescOnce.Do(func() {
		file_ubersdr_dsp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ubersdr_dsp_proto_rawDesc), len(file_ubersdr_dsp_proto_rawDesc)))
	})
	return file_ubersdr_dsp_proto_rawDescData
}

var file_ubersdr_dsp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ubersdr_dsp_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_ubersdr_dsp_proto_goTypes = []any{
	(PcmEncoding)(0),           // 0: ubersdr.dsp.v1.PcmEncoding
	(*AudioRequest)(nil),       // 1: ubersdr.dsp.v1.AudioRequest
	(*SessionConfig)(nil),      // 2: ubersdr.dsp.v1.SessionConfig
	(*ParamUpdate)(nil),        // 3: ubersdr.dsp.v1.ParamUpdate
	(*AudioChunk)(nil),         // 4: ubersdr.dsp.v1.AudioChunk
	(*AudioResponse)(nil),      // 5: ubersdr.dsp.v1.AudioResponse
	(*ParamAck)(nil),           // 6: ubersdr.dsp.v1.ParamAck
	(*ErrorResponse)(nil),      // 7: ubersdr.dsp.v1.ErrorResponse
	(*GetFiltersRequest)(nil),  // 8: ubersdr.dsp.v1.GetFiltersRequest
	(*GetFiltersResponse)(nil), // 9: ubersdr.dsp.v1.GetFiltersResponse
	(*FilterInfo)(nil),         // 10: ubersdr.dsp.v1.FilterInfo
	(*ParamInfo)(nil),          // 11: ubersdr.dsp.v1.ParamInfo
	nil,                        // 12: ubersdr.dsp.v1.SessionConfig.ParamsEntry
	nil,                        // 13: ubersdr.dsp.v1.ParamUpdate.ParamsEntry
	nil,                        // 14: ubersdr.dsp.v1.ParamAck.AppliedEntry
	nil,                        // 15: ubersdr.dsp.v1.ParamAck.RejectedEntry
}
var file_ubersdr_dsp_proto_depIdxs = []int32{
	2,  // 0: ubersdr.dsp.v1.AudioRequest.config:type_name -> ubersdr.dsp.v1.SessionConfig
	4,  // 1: ubersdr.dsp.v1.AudioRequest.audio:type_name -> ubersdr.dsp.v1.AudioChunk
	3,  // 2: ubersdr.dsp.v1.AudioRequest.param_update:type_name -> ubersdr.dsp.v1.ParamUpdate
	12, // 3: ubersdr.dsp.v1.SessionConfig.params:type_name -> ubersdr.dsp.v1.SessionConfig.ParamsEntry
	0,  // 4: ubersdr.dsp.v1.SessionConfig.pcm_encoding:type_name -> ubersdr.dsp.v1.PcmEncoding
	13, // 5: ubersdr.dsp.v1.ParamUpdate.params:type_name -> ubersdr.dsp.v1.ParamUpdate.ParamsEntry
	4,  // 6: ubersdr.dsp.v1.AudioResponse.audio:type_name -> ubersdr.dsp.v1.AudioChunk
	6,  // 7: ubersdr.dsp.v1.AudioResponse.ack:type_name -> ubersdr.dsp.v1.ParamAck
	7,  // 8: ubersdr.dsp.v1.AudioResponse.error:type_name -> ubersdr.dsp.v1.ErrorResponse
	14, // 9: ubersdr.dsp.v1.ParamAck.applied:type_name -> ubersdr.dsp.v1.ParamAck.AppliedEntry
	15, // 10: ubersdr.dsp.v1.ParamAck.rejected:type_name -> ubersdr.dsp.v1.ParamAck.RejectedEntry
	10, // 11: ubersdr.dsp.v1.GetFiltersResponse.filters:type_name -> ubersdr.dsp.v1.FilterInfo
	11, // 12: ubersdr.dsp.v1.FilterInfo.params:type_name -> ubersdr.dsp.v1.ParamInfo
	1,  // 13: ubersdr.dsp.v1.DspService.ProcessAudio:input_type -> ubersdr.dsp.v1.AudioRequest
	8,  // 14: ubersdr.dsp.v1.DspService.GetFilters:input_type -> ubersdr.dsp.v1.GetFiltersRequest
	5,  // 15: ubersdr.dsp.v1.DspService.ProcessAudio:output_type -> ubersdr.dsp.v1.AudioResponse
	9,  // 16: ubersdr.dsp.v1.DspService.GetFilters:output_type -> ubersdr.dsp.v1.GetFiltersResponse
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_ubersdr_dsp_proto_init() }
func file_ubersdr_dsp_proto_init() {
	if File_ubersdr_dsp_proto != nil {
		return
	}
	file_ubersdr_dsp_proto_msgTypes[0].OneofWrappers = []any{
		(*AudioRequest_Config)(nil),
		(*AudioRequest_Audio)(nil),
		(*AudioRequest_ParamUpdate)(nil),
	}
	file_ubersdr_dsp_proto_msgTypes[4].OneofWrappers = []any{
		(*AudioResponse_Audio)(nil),
		(*AudioResponse_Ack)(nil),
		(*AudioResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ubersdr_dsp_proto_rawDesc), len(file_ubersdr_dsp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ubersdr_dsp_proto_goTypes,
		DependencyIndexes: file_ubersdr_dsp_proto_depIdxs,
		EnumInfos:         file_ubersdr_dsp_proto_enumTypes,
		MessageInfos:      file_ubersdr_dsp_proto_msgTypes,
	}.Build()
	File_ubersdr_dsp_proto = out.File
	file_ubersdr_dsp_proto_goTypes = nil
	file_ubersdr_dsp_proto_depIdxs = nil
}
