// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: ubersdr_dsp.proto

package dsp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DspService_ProcessAudio_FullMethodName = "/ubersdr.dsp.v1.DspService/ProcessAudio"
	DspService_GetFilters_FullMethodName   = "/ubersdr.dsp.v1.DspService/GetFilters"
)

// DspServiceClient is the client API for DspService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DspServiceClient interface {
	// Bidirectional streaming audio processing.
	// First client message must be SessionConfig; subsequent messages are
	// AudioChunk or ParamUpdate. Server responds with AudioChunk, ParamAck,
	// or ErrorResponse payloads.
	ProcessAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioRequest, AudioResponse], error)
	// Unary: query available filters and their tunable parameters.
	GetFilters(ctx context.Context, in *GetFiltersRequest, opts ...grpc.CallOption) (*GetFiltersResponse, error)
}

type dspServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDspServiceClient(cc grpc.ClientConnInterface) DspServiceClient {
	return &dspServiceClient{cc}
}

func (c *dspServiceClient) ProcessAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioRequest, AudioResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DspService_ServiceDesc.Streams[0], DspService_ProcessAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioRequest, AudioResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DspService_ProcessAudioClient = grpc.BidiStreamingClient[AudioRequest, AudioResponse]

func (c *dspServiceClient) GetFilters(ctx context.Context, in *GetFiltersRequest, opts ...grpc.CallOption) (*GetFiltersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFiltersResponse)
	err := c.cc.Invoke(ctx, DspService_GetFilters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DspServiceServer is the server API for DspService service.
// All implementations must embed UnimplementedDspServiceServer
// for forward compatibility.
type DspServiceServer interface {
	// Bidirectional streaming audio processing.
	// First client message must be SessionConfig; subsequent messages are
	// AudioChunk or ParamUpdate. Server responds with AudioChunk, ParamAck,
	// or ErrorResponse payloads.
	ProcessAudio(grpc.BidiStreamingServer[AudioRequest, AudioResponse]) error
	// Unary: query available filters and their tunable parameters.
	GetFilters(context.Context, *GetFiltersRequest) (*GetFiltersResponse, error)
	mustEmbedUnimplementedDspServiceServer()
}

// UnimplementedDspServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDspServiceServer struct{}

func (UnimplementedDspServiceServer) ProcessAudio(grpc.BidiStreamingServer[AudioRequest, AudioResponse]) error {
	return status.Error(codes.Unimplemented, "method ProcessAudio not implemented")
}
func (UnimplementedDspServiceServer) GetFilters(context.Context, *GetFiltersRequest) (*GetFiltersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFilters not implemented")
}
func (UnimplementedDspServiceServer) mustEmbedUnimplementedDspServiceServer() {}
func (UnimplementedDspServiceServer) testEmbeddedByValue()                    {}

// UnsafeDspServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DspServiceServer will
// result in compilation errors.
type UnsafeDspServiceServer interface {
	mustEmbedUnimplementedDspServiceServer()
}

func RegisterDspServiceServer(s grpc.ServiceRegistrar, srv DspServiceServer) {
	// If the following call panics, it indicates UnimplementedDspServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DspService_ServiceDesc, srv)
}

func _DspService_ProcessAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DspServiceServer).ProcessAudio(&grpc.GenericServerStream[AudioRequest, AudioResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DspService_ProcessAudioServer = grpc.BidiStreamingServer[AudioRequest, AudioResponse]

func _DspService_GetFilters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFiltersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DspServiceServer).GetFilters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DspService_GetFilters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DspServiceServer).GetFilters(ctx, req.(*GetFiltersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DspService_ServiceDesc is the grpc.ServiceDesc for DspService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DspService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ubersdr.dsp.v1.DspService",
	HandlerType: (*DspServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFilters",
			Handler:    _DspService_GetFilters_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessAudio",
			Handler:       _DspService_ProcessAudio_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ubersdr_dsp.proto",
}
