#!/bin/sh
# Caddy entrypoint script
# Waits for ubersdr to generate the Caddyfile before starting Caddy

CADDYFILE="/etc/caddy-shared/Caddyfile"
MAX_WAIT=60  # Maximum wait time in seconds
WAIT_INTERVAL=2  # Check every 2 seconds

echo "Waiting for Caddyfile to be generated by ubersdr..."
elapsed=0

while [ ! -f "$CADDYFILE" ] && [ $elapsed -lt $MAX_WAIT ]; do
    echo "Waiting for $CADDYFILE... (${elapsed}s/${MAX_WAIT}s)"
    sleep $WAIT_INTERVAL
    elapsed=$((elapsed + WAIT_INTERVAL))
done

if [ ! -f "$CADDYFILE" ]; then
    echo "ERROR: Caddyfile not found after ${MAX_WAIT} seconds"
    echo "ubersdr may not have started properly or failed to generate the Caddyfile"
    exit 1
fi

echo "Caddyfile found! Starting Caddy..."
exec caddy run --config "$CADDYFILE" --adapter caddyfile